/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack_formularios;

/**
 *
 * @author canow
 */
public class formEjemplo1 extends javax.swing.JFrame {

    /**
     * Creates new form formEjemplo1
     */
    public formEjemplo1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumero1 = new javax.swing.JLabel();
        txtNumero1 = new javax.swing.JTextField();
        btnFor = new javax.swing.JButton();
        btnWhile = new javax.swing.JButton();
        btnDowhile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRespuesta = new javax.swing.JTextArea();
        btnMcd = new javax.swing.JButton();
        lblNumero2 = new javax.swing.JLabel();
        txtNumero2 = new javax.swing.JTextField();
        btnVector = new javax.swing.JButton();
        btnMatriz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNumero1.setText("Numero 1 :");

        btnFor.setText("For");
        btnFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForActionPerformed(evt);
            }
        });

        btnWhile.setText("While");
        btnWhile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWhileActionPerformed(evt);
            }
        });

        btnDowhile.setText("Do while");
        btnDowhile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDowhileActionPerformed(evt);
            }
        });

        txtRespuesta.setColumns(20);
        txtRespuesta.setRows(5);
        jScrollPane1.setViewportView(txtRespuesta);

        btnMcd.setText("MCD");
        btnMcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMcdActionPerformed(evt);
            }
        });

        lblNumero2.setText("Numero 2 :");

        btnVector.setText("Vector");
        btnVector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVectorActionPerformed(evt);
            }
        });

        btnMatriz.setText("Matriz");
        btnMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatrizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(btnMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnFor)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnWhile)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDowhile)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNumero1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNumero2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnVector))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMcd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero1)
                    .addComponent(txtNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumero2)
                    .addComponent(txtNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFor)
                    .addComponent(btnWhile)
                    .addComponent(btnDowhile)
                    .addComponent(btnMcd)
                    .addComponent(btnVector))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btnMatriz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForActionPerformed
        // TODO add your handling code here:
        int num, i, producto;
        num = Integer.parseInt(txtNumero1.getText());
        
        //Logica
        txtRespuesta.setText("Tabla de multiplicar con bucle = for\n");
        
        for(i=1; i<=12; i++){
            producto=num*i;
            //Escribimos respuesta
            txtRespuesta.append(num+" x "+i+" = "+producto+"\n");
        }
    }//GEN-LAST:event_btnForActionPerformed

    private void btnWhileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWhileActionPerformed
        // TODO add your handling code here:
        int num, i=1, producto;
        num = Integer.parseInt(txtNumero1.getText());
        
        //Logica
        txtRespuesta.setText("Tabla de multiplicar con bucle = while\n");
        
        while(i<=12){
            producto=num*i;
            //Escribimos respuesta
            txtRespuesta.append(num+" x "+i+" = "+producto+"\n");
            i++;
        }
    }//GEN-LAST:event_btnWhileActionPerformed

    private void btnDowhileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDowhileActionPerformed
        // TODO add your handling code here:
        int num, i=1, producto;
        num = Integer.parseInt(txtNumero1.getText());
        
        //Logica
        txtRespuesta.setText("Tabla de multiplicar con bucle = do while\n");
        
        do{
            producto=num*i;
            //Escribimos respuesta
            txtRespuesta.append(num+" x "+i+" = "+producto+"\n");
            i++;
        }while(i<=12);
    }//GEN-LAST:event_btnDowhileActionPerformed

    private void btnMcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMcdActionPerformed
        // TODO add your handling code here:
        int a, b, residuo=-1;
        int aux, aux_a, aux_b;
        //Lectura de datos
        a = Integer.parseInt(txtNumero1.getText());
        b = Integer.parseInt(txtNumero2.getText());
        
        aux_a = a;
        aux_b = b;
        
        if(a>b){
            aux=a;
            a=b;
            b=aux;
        }
        
        txtRespuesta.setText("Calculamos el MCD de los numeros"+a+" y "+b+"paso a paso\n");
        
        while(residuo!=0){
            txtRespuesta.append("MCD("+a+", "+b+") = ");
            residuo=a%b;
            a=b;
            b=residuo;
            txtRespuesta.append("El MCD de "+aux_a+" y "+aux_b+" es: "+a+"\n");
        }
        txtRespuesta.append("El MCD de "+aux_a+" y "+aux_b+" es: "+a+"\n");
    }//GEN-LAST:event_btnMcdActionPerformed

    private void btnVectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVectorActionPerformed
        // TODO add your handling code here:
        
        int[] notas = {15,18,20,16,7,4,12,15,14,17};
        txtRespuesta.setText("Los elementos del arreglo son:\n");
        System.out.println(notas.length);
        
        for(int i=0;i<=((notas.length)-1);i++){
            txtRespuesta.append(""+notas[i]+"\n");
        }
       
    }//GEN-LAST:event_btnVectorActionPerformed

    private void btnMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatrizActionPerformed
        // TODO add your handling code here:
        
        int [][] notas= {{2,3,4},{9,10,11}};
        int i=0, j=0;
        
        txtRespuesta.setText("Los elementos de la matriz son: \n");
        for(i = 0;i<notas.length;i++){
            for(j = 0;j<notas[i].length;j++){
                txtRespuesta.append(notas[i][j]+"");
            }
            txtRespuesta.append("\n");
        }
        
    }//GEN-LAST:event_btnMatrizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formEjemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formEjemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formEjemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formEjemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formEjemplo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDowhile;
    private javax.swing.JButton btnFor;
    private javax.swing.JButton btnMatriz;
    private javax.swing.JButton btnMcd;
    private javax.swing.JButton btnVector;
    private javax.swing.JButton btnWhile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNumero1;
    private javax.swing.JLabel lblNumero2;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero2;
    private javax.swing.JTextArea txtRespuesta;
    // End of variables declaration//GEN-END:variables
}
